encoding: utf-8

# Site Settings
baseurl: ""
url : "https://YGYoon71.github.io"

# Blog Settings
theme_settings :
  title : DO8's GitHub BLOG
  favicon : assets/favicon.ico

  # Profile Settings
  profile :
    image : assets/img/smile.png
    username : YongGeun YOON
    description : 디지털트윈 시스템이란 현실세계의 사물을 가상현실로 복제하여 현실에서 발생하는 상황을 가상현실에서 모니터링하고, 가상현실에서 다양한 환경 변수에 의한 실험을 통해 현실 세계에서 사물에 일어날 수 있는 변화를 예측하여 가상현실로부터 현실 세계의 사물을 제어하는 시스템.
    experience :
      - start : 2017-08
        end : ...ing
        experience : NamoWebiz, Inc., title
    skills :
      - skill : HTML5 & CSS
        value : 85  # Percent value

  # Icons
  icons :
    email:  ygyoon@gmail.com # Full email address, e.g. "sample@google.com"
    linkedin:  # Full URL
    github: YGYoon71
    gitlab:
    bitbucket:
    google_plus:
    twitter:
    youtube:
    facebook: yonggeuny
    instagram: yoonyonggeun

  # Disqus
  disqus_shortname :do8

# Pagination
paginate: 5
paginate_path: "blog/page:num"

# Build Ssttings
sass:
  sass_dir: _sass
  style: :compressed
gems: [jekyll-paginate]
bootstrap:
  assets: true
